### ISSUE TITLE
Gettin an exception/error: 'Not a compressed Palworld save, found b'\x00\x00\x00' instead of P1Z'

### ISSUE THREAD

**Issue by Nicola-T** [jmkl009/PalworldCharacterTransfer#14]
Not sure why this is happening, hoping you could shine some light on what is going wrong. Was able to transfer my character successfully but I get this error when trying to transfer the other two players on the server: 

"file open time:  0.001005411148071289
file read time:  0.0
file decompress time:  0.0
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\nicot\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\nicot\.cargo\bin\char-export.py", line 501, in main
    targ_json_gvas = load_player_file(t_level_sav_path, selected_target_player)
  File "C:\Users\nicot\.cargo\bin\char-export.py", line 935, in load_player_file
    raw_gvas, _ = load_file(player_file_path)
  File "C:\Users\nicot\.cargo\bin\char-export.py", line 926, in load_file
    loaded_file, save_type = sav_to_gvas(path)
  File "C:\Users\nicot\.cargo\bin\char-export.py", line 889, in sav_to_gvas
    raw_gvas, save_type = decompress_sav_to_gvas(data)
  File "C:\Users\nicot\.cargo\bin\lib\palsav.py", line 11, in decompress_sav_to_gvas
    raise Exception(
Exception: not a compressed Palworld save, found b'\x00\x00\x00' instead of P1Z"

Thanks a ton in advance for your time and help with this!

**Comment by jmkl009** [comment]
The save files are corrupted, there is no way to salvage it as far as I know, as opening the binary file shows all bytes as zero, which means all data is lost.
