### ISSUE TITLE
V1.3.3遇到错误🥲🥲

### ISSUE THREAD

**Issue by yycmonj** [jmkl009/PalworldCharacterTransfer#17]
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "char-export-zh.py", line 765, in main
  File "char-export-zh.py", line 130, in curr_property
  File "lib\archive.py", line 164, in fstring
struct.error: unpack requires a buffer of 4 bytes

**Comment by jingjin9** [comment]
帕鲁更新后的问题。你能attach一个level.sav和players么这样我好测试。

**Comment by jmkl009** [comment]
帕鲁更新后的问题。你能attach一个level.sav和players么这样我好测试。

**Comment by jmkl009** [comment]
push了一个fix，你可以试一下

**Comment by yycmonj** [comment]
成功了，多谢！
