### ISSUE TITLE
char-export.py KeyError b\x00\x00\

### ISSUE THREAD

**Issue by MidnightZealot** [jmkl009/PalworldCharacterTransfer#25]
Everything about the process works without issue until it gets to the character export then I get a repeating Null KeyError.
This happens with any of the three characters that were in the original world as I tested each one to make sure it wasn't just my char file.

(Note: The character I am trying to transfer to Steam was created when Palworld was first launched on XB Gamepass.)

found instance
Found Character Parameter Map
Read 292 pals from source save
Searching for container data
Found host otomo inventory
Found host pal inventory
Found all pal containers
Found host main inventory
Found host key inventory
Found host weapon inventory
Found host armor inventory
Found host food bag inventory
Found all target containers
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "char-export.py", line 605, in main
**KeyError: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'**

**Comment by ll-FEROX-ll** [comment]
Same, any update?

Thank you!!!
