### ISSUE TITLE
Broken after Feybreak update

### ISSUE THREAD

**Issue by ken1882** [jmkl009/PalworldCharacterTransfer#27]
Does not work anymore after the Feybreak update
```
>python char-export.py
Property GroupSaveDataMap loaded in 0.0029299259185791016 seconds, total time including find: 0.0039052963256835938
Property CharacterSaveParameterMap loaded in 0.04198813438415527 seconds, total time including find: 0.04198813438415527
Property ItemContainerSaveData loaded in 0.20325016975402832 seconds, total time including find: 0.27407240867614746
Property DynamicItemSaveData loaded in 0.027338743209838867 seconds, total time including find: 0.02831745147705078
Property CharacterContainerSaveData loaded in 0.0009758472442626953 seconds, total time including find: 0.0019538402557373047
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Compeador\anaconda3\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "G:\pal\PalworldCharacterTransfer\char-export.py", line 1041, in target_level_file
    group_save_section, group_save_section_range = reader.load_section('GroupSaveDataMap', MAP_START, reverse=True)
  File "G:\pal\PalworldCharacterTransfer\char-export.py", line 183, in load_section
    prop = self.curr_property(path=path)
  File "G:\pal\PalworldCharacterTransfer\char-export.py", line 133, in curr_property
    properties[name] = self.property(type_name, size, f"{path}.{name}")
  File "G:\pal\PalworldCharacterTransfer\lib\archive.py", line 289, in property
    value = self.custom_properties[path][0](self, type_name, size, path)
  File "G:\pal\PalworldCharacterTransfer\char-export.py", line 294, in decode_group
    group["value"]["RawData"]["value"] = decode_bytes(
  File "G:\pal\PalworldCharacterTransfer\char-export.py", line 337, in decode_bytes
    "last_online_real_time": reader.i64(),
  File "G:\pal\PalworldCharacterTransfer\lib\archive.py", line 216, in i64
    return FArchiveReader.unpack_i64(self.data.read(8))[0]
struct.error: unpack requires a buffer of 8 bytes
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Compeador\anaconda3\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "G:\pal\PalworldCharacterTransfer\char-export.py", line 1041, in target_level_file
    group_save_section, group_save_section_range = reader.load_section('GroupSaveDataMap', MAP_START, reverse=True)
  File "G:\pal\PalworldCharacterTransfer\char-export.py", line 181, in load_section
    self.data.seek(start_index, 0)
ValueError: negative seek value -1
```

**Comment by vadidian** [comment]
It appears the new save file format adds a 16bit value after reading the guild data. I'm currently unsure what this value means, but skipping it will allow the read process to finish. However, the writing/transfer process will crash presumably due to this missing value.

**Comment by ferreyr9** [comment]
I did manage to make it work, but there is still some minor issues

**Comment by BrickNeck** [comment]
> I did manage to make it work, but there is still some minor issues

Do you mind sharing?

**Comment by eduwalecki** [comment]
> > I did manage to make it work, but there is still some minor issues
> 
> Do you mind sharing?

Just try with his changed fork files at https://github.com/Ferreira-Tagamer/PalworldCharacterTransfer and it works, used the level file because player file got error here. 

Thanks @Ferreira-Tagamer

**Comment by WECI-Jake** [comment]
Hey @Ferreira-Tagamer,  I'm trying to use this to load a save and i run into the same issue as issue #29 above this one.   Did you run into this while testing your changes on the script?

**Comment by BallisticCrazer** [comment]
@Ferreira-Tagamer Consegue ajudar a gente nessa eu apliquei suas mudanças e mesmo assim estou tendo esse error:

xception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "c:\Users\ferna\Desktop\PalworldCharacterTransfer-main\char-export.py", line 991, in source_level_file
    group_save_section, _ = reader.load_section('GroupSaveDataMap', MAP_START, reverse=True)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ferna\Desktop\PalworldCharacterTransfer-main\char-export.py", line 181, in load_section
    self.data.seek(start_index, 0)
ValueError: negative seek value -1

**Comment by BallisticCrazer** [comment]
@Ferreira-Tagamer  Can you help me via discord please add me there, I need help with something related to palworld, my nickname: ballisticcrazer, I'm having difficulties with the world transfer, I just need to change the world host, my friend can't do it I played more often, then he wanted to send the world to me and then I could open the world and play co-op again, but neither he nor I lost progress
